<?php
return [
    'cities' => [
        'SG' => array(
            'text' => 'Hồ Chí Minh',
            'districts' => array(
                1 => 'Quận 1',
                2 => 'Quận 2',
                3 => 'Quận 3',
                4 => 'Quận 4',
                5 => 'Quận 5',
                6 => 'Quận 6',
                7 => 'Quận 7',
                8 => 'Quận 8',
                9 => 'Quận 9',
                10 => 'Quận 10',
                11 => 'Quận 11',
                12 => 'Quận 12',
                13 => 'Bình Tân',
                14 => 'Bình Thạnh',
                15 => 'Gò Vấp',
                16 => 'Phú Nhuận',
                17 => 'Tân Bình',
                18 => 'Tân Phú',
                19 => 'Thủ Đức',
                20 => 'Bình Chánh',
                21 => 'Cần Giờ',
                22 => 'Củ Chi',
                23 => 'Hóc Môn',
                24 => 'Nhà Bè',
            ),
        ),
        'HN' => array(
            'text' => 'Hà Nội',
            'districts' => array(
                25 => 'Hoàn Kiếm',
                26 => 'Ba Đình',
                27 => 'Đống Đa',
                28 => 'Hai Bà Trưng',
                29 => 'Thanh Xuân',
                30 => 'Tây Hồ',
                31 => 'Cầu Giấy',
                32 => 'Hoàng Mai',
                33 => 'Long Biên',
                34 => 'Đông Anh',
                35 => 'Gia Lâm',
                36 => 'Sóc Sơn',
                37 => 'Thanh Trì',
                38 => 'Nam Từ Liêm',
                39 => 'Hà Đông',
                40 => 'Bắc Từ Liêm',
                41 => 'Sơn Tây',
                42 => 'Mê Linh',
                43 => 'Ba Vì',
                44 => 'Phúc Thọ',
                45 => 'Đan Phượng',
                46 => 'Hoài Đức',
                47 => 'Quốc Oai',
                48 => 'Thạch Thất',
                49 => 'Chương Mỹ',
                50 => 'Thanh Oai',
                51 => 'Thường Tín',
                52 => 'Phú Xuyên',
                53 => 'Ứng Hòa',
                54 => 'Mỹ Đức',
            ),
        ),
        'DDN' => array(
            'text' => 'Đà Nẵng',
            'districts' => array(
                55 => 'Cẩm Lệ',
                56 => 'Hải Châu',
                57 => 'Liên Chiểu',
                58 => 'Ngũ Hành Sơn',
                59 => 'Sơn Trà',
                60 => 'Thanh Khê',
                61 => 'Hòa Vang',
                62 => 'Hoàng Sa',
            ),
        ),
        'BD' => array(
            'text' => 'Bình Dương',
            'districts' => array(
                63 => 'Bến Cát',
                64 => 'Dầu Tiếng',
                65 => 'Dĩ An',
                66 => 'Phú Giáo',
                67 => 'Tân Uyên',
                68 => 'Thuận An',
                69 => 'Thủ Dầu Một',
                70 => 'Bàu Bàng',
                71 => 'Bắc Tân Uyên',
            ),
        ),
        'DNA' => array(
            'text' => 'Đồng Nai',
            'districts' => array(
                72 => 'Cẩm Mỹ',
                73 => 'Định Quán',
                74 => 'Long Thành',
                75 => 'Nhơn Trạch',
                76 => 'Tân Phú',
                77 => 'Thống Nhất',
                78 => 'Trảng Bom',
                79 => 'Vĩnh Cửu',
                80 => 'Xuân Lộc',
                81 => 'Biên Hòa',
                82 => 'Long Khánh',
            ),
        ),
        'KH' => array(
            'text' => 'Khánh Hòa',
            'districts' => array(
                83 => 'Cam Lâm',
                84 => 'Diên Khánh',
                85 => 'Khánh Sơn',
                86 => 'Khánh Vĩnh',
                87 => 'Ninh Hòa',
                88 => 'Trường Sa',
                89 => 'Vạn Ninh',
                90 => 'Nha Trang',
                91 => 'Cam Ranh',
            ),
        ),
        'HP' => array(
            'text' => 'Hải Phòng',
            'districts' => array(
                92 => 'Đồ Sơn',
                93 => 'Dương Kinh',
                94 => 'Hải An',
                95 => 'Hồng Bàng',
                96 => 'Kiến An',
                97 => 'Lê Chân',
                98 => 'Ngô Quyền',
                99 => 'An Dương',
                100 => 'An Lão',
                101 => 'Bạch Long Vĩ',
                102 => 'Cát Hải',
                103 => 'Kiến Thụy',
                104 => 'Thủy Nguyên',
                105 => 'Tiên Lãng',
                106 => 'Vĩnh Bảo',
            ),
        ),
        'LA' => array(
            'text' => 'Long An',
            'districts' => array(
                107 => 'Bến Lức',
                108 => 'Cần Đước',
                109 => 'Cần Giuộc',
                110 => 'Châu Thành',
                111 => 'Đức Hòa',
                112 => 'Đức Huệ',
                113 => 'Mộc Hóa',
                114 => 'Tân Hưng',
                115 => 'Tân Thạnh',
                116 => 'Tân Trụ',
                117 => 'Thạnh Hóa',
                118 => 'Thủ Thừa',
                119 => 'Vĩnh Hưng',
                120 => 'Tân An',
                121 => 'Kiến Tường',
            ),
        ),
        'QNA' => array(
            'text' => 'Quảng Nam',
            'districts' => array(
                122 => 'Bắc Trà My',
                123 => 'Đại Lộc',
                124 => 'Điện Bàn',
                125 => 'Đông Giang',
                126 => 'Duy Xuyên',
                127 => 'Hiệp Đức',
                128 => 'Nam Giang',
                129 => 'Nam Trà My',
                130 => 'Núi Thành',
                131 => 'Phú Ninh',
                132 => 'Phước Sơn',
                133 => 'Quế Sơn',
                134 => 'Tây Giang',
                135 => 'Thăng Bình',
                136 => 'Tiên Phước',
                137 => 'Tam Kỳ',
                138 => 'Hội An',
                139 => 'Nông Sơn',
            ),
        ),
        'VT' => array(
            'text' => 'Bà Rịa Vũng Tàu',
            'districts' => array(
                140 => 'Châu Đức',
                141 => 'Côn Đảo',
                142 => 'Đất Đỏ',
                143 => 'Long Điền',
                144 => 'Phú Mỹ',
                145 => 'Xuyên Mộc',
                146 => 'Vũng Tàu',
                147 => 'Bà Rịa',
            ),
        ),
        'DDL' => array(
            'text' => 'Đắk Lắk',
            'districts' => array(
                148 => 'Buôn Đôn',
                149 => 'Cư Kuin',
                150 => 'Cư M\'gar',
                151 => 'Ea H\'Leo',
                152 => 'Ea Kar',
                153 => 'Ea Súp',
                154 => 'Krông Ana',
                155 => 'Krông Bông',
                156 => 'Krông Buk',
                157 => 'Krông Năng',
                158 => 'Krông Pắc',
                159 => 'Lăk',
                160 => 'M\'Đrăk',
                161 => 'Buôn Ma Thuột',
                162 => 'Buôn Hồ',
            ),
        ),
        'CT' => array(
            'text' => 'Cần Thơ',
            'districts' => array(
                163 => 'Cờ Đỏ',
                164 => 'Phong Điền',
                165 => 'Thốt Nốt',
                166 => 'Vĩnh Thạnh',
                167 => 'Bình Thủy',
                168 => 'Cái Răng',
                169 => 'Ninh Kiều',
                170 => 'Ô Môn',
                171 => ' Thới Lai',
            ),
        ),
        'BTH' => array(
            'text' => 'Bình Thuận  ',
            'districts' => array(
                172 => 'Bắc Bình',
                173 => 'Đảo Phú Quý',
                174 => 'Đức Linh',
                175 => 'Hàm Tân',
                176 => 'Hàm Thuận Bắc',
                177 => 'Hàm Thuận Nam',
                178 => 'Tánh Linh',
                179 => 'Tuy Phong',
                180 => 'Phan Thiết',
                181 => 'La Gi',
            ),
        ),
        'LDD' => array(
            'text' => 'Lâm Đồng',
            'districts' => array(
                182 => 'Bảo Lâm',
                183 => 'Cát Tiên',
                184 => 'Đạ Huoai',
                185 => 'Đạ Tẻh',
                186 => 'Đam Rông',
                187 => 'Di Linh',
                188 => 'Đơn Dương',
                189 => 'Đức Trọng',
                190 => 'Lạc Dương',
                191 => 'Lâm Hà',
                192 => 'Đà Lạt',
                193 => 'Bảo Lộc',
            ),
        ),
        'TTH' => array(
            'text' => 'Thừa Thiên Huế',
            'districts' => array(
                194 => 'A Lưới',
                195 => 'Hương Thủy',
                196 => 'Hương Trà',
                197 => 'Nam Đông',
                198 => 'Phong Điền',
                199 => 'Phú Lộc',
                200 => 'Phú Vang',
                201 => 'Quảng Điền',
                202 => 'Huế',
            ),
        ),
        'KG' => array(
            'text' => 'Kiên Giang',
            'districts' => array(
                203 => 'An Biên',
                204 => 'An Minh',
                205 => 'Châu Thành',
                206 => 'Giồng Riềng',
                207 => 'Gò Quao',
                208 => 'Hòn Đất',
                209 => 'Kiên Hải',
                210 => 'Kiên Lương',
                211 => 'Phú Quốc',
                212 => 'Tân Hiệp',
                213 => 'U minh Thượng',
                214 => 'Vĩnh Thuận',
                215 => 'Rạch Giá',
                216 => 'Hà Tiên',
                217 => 'Giang Thành',
            ),
        ),
        'BN' => array(
            'text' => 'Bắc Ninh',
            'districts' => array(
                218 => 'Gia Bình',
                219 => 'Lương Tài',
                220 => 'Quế Võ',
                221 => 'Thuận Thành',
                222 => 'Tiên Du',
                223 => 'Từ Sơn',
                224 => 'Yên Phong',
                225 => 'Bắc Ninh',
            ),
        ),
        'QNI' => array(
            'text' => 'Quảng Ninh',
            'districts' => array(
                226 => 'Ba Chẽ',
                227 => 'Bình Liêu',
                228 => 'Cô Tô',
                229 => 'Đầm Hà',
                230 => 'Đông Triều',
                231 => 'Hải Hà',
                232 => 'Hoành Bồ',
                233 => 'Tiên Yên',
                234 => 'Vân Đồn',
                235 => 'Hạ Long',
                236 => 'Cẩm Phả',
                237 => 'Móng Cái',
                238 => 'Uông Bí',
                239 => 'Quảng Yên',
            ),
        ),
        'TH' => array(
            'text' => 'Thanh Hóa',
            'districts' => array(
                240 => 'Bá Thước',
                241 => 'Cẩm Thủy',
                242 => 'Đông Sơn',
                243 => 'Hà Trung',
                244 => 'Hậu Lộc',
                245 => 'Hoằng Hóa',
                246 => 'Lang Chánh',
                247 => 'Mường Lát',
                248 => 'Nga Sơn',
                249 => 'Ngọc Lặc',
                250 => 'Như Thanh',
                251 => 'Như Xuân',
                252 => 'Nông Cống',
                253 => 'Quan Hóa',
                254 => 'Quan Sơn',
                255 => 'Quảng Xương',
                256 => 'Thạch Thành',
                257 => 'Thiệu Hóa',
                258 => 'Thọ Xuân',
                259 => 'Thường Xuân',
                260 => 'Tĩnh Gia',
                261 => 'Triệu Sơn',
                262 => 'Vĩnh Lộc',
                263 => 'Yên Định',
                264 => 'Thanh Hóa',
                265 => 'Bỉm Sơn',
                266 => 'Sầm Sơn',
            ),
        ),
        'NA' => array(
            'text' => 'Nghệ An',
            'districts' => array(
                267 => 'Anh Sơn',
                268 => 'Con Cuông',
                269 => 'Diễn Châu',
                270 => 'Đô Lương',
                271 => 'Hưng Nguyên',
                272 => 'Kỳ Sơn',
                273 => 'Nam Đàn',
                274 => 'Nghi Lộc',
                275 => 'Nghĩa Đàn',
                276 => 'Quế Phong',
                277 => 'Quỳ Châu',
                278 => 'Quỳ Hợp',
                279 => 'Quỳnh Lưu',
                280 => 'Tân Kỳ',
                281 => 'Thanh Chương',
                282 => 'Tương Dương',
                283 => 'Yên Thành',
                284 => 'Vinh',
                285 => 'Cửa Lò',
                286 => 'Thái Hòa',
                287 => 'Hoàng Mai',
            ),
        ),
        'HD' => array(
            'text' => 'Hải Dương',
            'districts' => array(
                288 => 'Bình Giang',
                289 => 'Cẩm Giàng',
                290 => 'Chí Linh',
                291 => 'Gia Lộc',
                292 => 'Kim Thành',
                293 => 'Kinh Môn',
                294 => 'Nam Sách',
                295 => 'Ninh Giang',
                296 => 'Thanh Hà',
                297 => 'Thanh Miện',
                298 => 'Tứ Kỳ',
                299 => 'Hải Dương',
            ),
        ),
        'GL' => array(
            'text' => 'Gia Lai',
            'districts' => array(
                300 => 'AYun Pa',
                301 => 'Chư Păh',
                302 => 'Chư Sê',
                303 => 'ChưPRông',
                304 => 'Đăk Đoa',
                305 => 'Đăk Pơ',
                306 => 'Đức Cơ',
                307 => 'Ia Grai',
                308 => 'Ia Pa',
                309 => 'KBang',
                310 => 'Kông Chro',
                311 => 'Krông Pa',
                312 => 'Mang Yang',
                313 => 'Phú Thiện',
                314 => 'Plei Ku',
                315 => 'An Khê',
                316 => 'Chư Pưh',
            ),
        ),
        'BP' => array(
            'text' => 'Bình Phước',
            'districts' => array(
                317 => 'Bình Long',
                318 => 'Bù Đăng',
                319 => 'Bù Đốp',
                320 => 'Chơn Thành',
                321 => 'Đồng Phú',
                322 => 'Lộc Ninh',
                323 => 'Phước Long',
                324 => 'Đồng Xoài',
                325 => 'Hớn Quản',
                326 => 'Bù Gia Mập',
                327 => 'Phú Riềng',
            ),
        ),
        'HY' => array(
            'text' => 'Hưng Yên',
            'districts' => array(
                328 => 'Ân Thi',
                329 => 'Khoái Châu',
                330 => 'Kim Động',
                331 => 'Mỹ Hào',
                332 => 'Phù Cừ',
                333 => 'Tiên Lữ',
                334 => 'Văn Giang',
                335 => 'Văn Lâm',
                336 => 'Yên Mỹ',
                337 => 'Hưng Yên',
            ),
        ),
        'BDD' => array(
            'text' => 'Bình Định',
            'districts' => array(
                338 => 'An Lão',
                339 => 'An Nhơn',
                340 => 'Hoài Ân',
                341 => 'Hoài Nhơn',
                342 => 'Phù Cát',
                343 => 'Phù Mỹ',
                344 => 'Tây Sơn',
                345 => 'Tuy Phước',
                346 => 'Vân Canh',
                347 => 'Vĩnh Thạnh',
                348 => 'Quy Nhơn',
            ),
        ),
        'TG' => array(
            'text' => 'Tiền Giang',
            'districts' => array(
                349 => 'Cái Bè',
                350 => 'Huyện Cai Lậy',
                351 => 'Châu Thành',
                352 => 'Chợ Gạo',
                353 => 'Gò Công Đông',
                354 => 'Gò Công Tây',
                355 => 'Tân Phước',
                356 => 'Tân Phú Đông',
                357 => 'Mỹ Tho',
                358 => 'Gò Công',
                359 => 'Cai Lậy',
            ),
        ),
        'TB' => array(
            'text' => 'Thái Bình',
            'districts' => array(
                360 => 'Đông Hưng',
                361 => 'Hưng Hà',
                362 => 'Kiến Xương',
                363 => 'Quỳnh Phụ',
                364 => 'Thái Thuỵ',
                365 => 'Tiền Hải',
                366 => 'Vũ Thư',
                367 => 'Thái Bình',
            ),
        ),
        'BG' => array(
            'text' => 'Bắc Giang',
            'districts' => array(
                368 => 'Hiệp Hòa',
                369 => 'Lạng Giang',
                370 => 'Lục Nam',
                371 => 'Lục Ngạn',
                372 => 'Sơn Động',
                373 => 'Tân Yên',
                374 => 'Việt Yên',
                375 => 'Yên Dũng',
                376 => 'Yên Thế',
                377 => 'Bắc Giang',
            ),
        ),
        'HB' => array(
            'text' => 'Hòa Bình',
            'districts' => array(
                378 => 'Cao Phong',
                379 => 'Đà Bắc',
                380 => 'Kim Bôi',
                381 => 'Kỳ Sơn',
                382 => 'Lạc Sơn',
                383 => 'Lạc Thủy',
                384 => 'Lương Sơn',
                385 => 'Mai Châu',
                386 => 'Tân Lạc',
                387 => 'Yên Thủy',
                388 => 'Hòa Bình',
            ),
        ),
        'AG' => array(
            'text' => 'An Giang',
            'districts' => array(
                389 => 'An Phú',
                390 => 'Châu Phú',
                391 => 'Châu Thành',
                392 => 'Chợ Mới',
                393 => 'Tri Tôn',
                394 => 'Phú Tân',
                395 => 'Tân Châu',
                396 => 'Thoại Sơn',
                397 => 'Tịnh Biên',
                398 => 'Long Xuyên',
                399 => 'Châu Đốc',
            ),
        ),
        'VP' => array(
            'text' => 'Vĩnh Phúc',
            'districts' => array(
                400 => 'Bình Xuyên',
                401 => 'Lập Thạch',
                402 => 'Tam Đảo',
                403 => 'Tam Dương',
                404 => 'Vĩnh Tường',
                405 => 'Yên Lạc',
                406 => 'Vĩnh Yên',
                407 => 'Phúc Yên',
                408 => 'Sông Lô',
            ),
        ),
        'TNI' => array(
            'text' => 'Tây Ninh',
            'districts' => array(
                409 => 'Bến Cầu',
                410 => 'Châu Thành',
                411 => 'Dương Minh Châu',
                412 => 'Gò Dầu',
                413 => 'Hòa Thành',
                414 => 'Tân Biên',
                415 => 'Tân Châu',
                416 => 'Trảng Bàng',
                417 => 'Tây Ninh',
            ),
        ),
        'TN' => array(
            'text' => 'Thái Nguyên',
            'districts' => array(
                418 => 'Đại Từ',
                419 => 'Định Hóa',
                420 => 'Đồng Hỷ',
                421 => 'Phổ Yên',
                422 => 'Phú Bình',
                423 => 'Phú Lương',
                424 => 'Võ Nhai',
                425 => 'Thái Nguyên',
                426 => 'Sông Công',
            ),
        ),
        'LCA' => array(
            'text' => 'Lào Cai',
            'districts' => array(
                427 => 'Bắc Hà',
                428 => 'Bảo Thắng',
                429 => 'Bảo Yên',
                430 => 'Bát Xát',
                431 => 'Mường Khương',
                432 => 'Sa Pa',
                433 => 'Văn Bàn',
                434 => 'Xi Ma Cai',
                435 => 'Lào Cai',
            ),
        ),
        'NDD' => array(
            'text' => 'Nam Định',
            'districts' => array(
                436 => 'Giao Thủy',
                437 => 'Hải Hậu',
                438 => 'Mỹ Lộc',
                439 => 'Nam Trực',
                440 => 'Nghĩa Hưng',
                441 => 'Trực Ninh',
                442 => 'Vụ Bản',
                443 => 'Xuân Trường',
                444 => 'Ý Yên',
                445 => 'Nam Định',
            ),
        ),
        'QNG' => array(
            'text' => 'Quảng Ngãi',
            'districts' => array(
                446 => 'Ba Tơ',
                447 => 'Bình Sơn',
                448 => 'Đức Phổ',
                449 => 'Lý Sơn',
                450 => 'Minh Long',
                451 => 'Mộ Đức',
                452 => 'Nghĩa Hành',
                453 => 'Sơn Hà',
                454 => 'Sơn Tây',
                455 => 'Sơn Tịnh',
                456 => 'Tây Trà',
                457 => 'Trà Bồng',
                458 => 'Tư Nghĩa',
                459 => 'Quảng Ngãi',
            ),
        ),
        'BTR' => array(
            'text' => 'Bến Tre',
            'districts' => array(
                460 => 'Ba Tri',
                461 => 'Bình Đại',
                462 => 'Châu Thành',
                463 => 'Chợ Lách',
                464 => 'Giồng Trôm',
                465 => 'Thạnh Phú',
                466 => 'Bến Tre',
                467 => 'Mỏ Cày Bắc',
                468 => 'Mỏ Cày Nam',
            ),
        ),
        'DNO' => array(
            'text' => 'Đắk Nông',
            'districts' => array(
                469 => 'Cư Jút',
                470 => 'Dăk GLong',
                471 => 'Dăk Mil',
                472 => 'Dăk R\'Lấp',
                473 => 'Dăk Song',
                474 => 'Krông Nô',
                475 => 'Tuy Đức',
                476 => 'Gia Nghĩa',
            ),
        ),
        'CM' => array(
            'text' => 'Cà Mau',
            'districts' => array(
                477 => 'Cái Nước',
                478 => 'Đầm Dơi',
                479 => 'Năm Căn',
                480 => 'Ngọc Hiển',
                481 => 'Phú Tân',
                482 => 'Thới Bình',
                483 => 'Trần Văn Thời',
                484 => 'U Minh',
                485 => 'Cà Mau',
            ),
        ),
        'VL' => array(
            'text' => 'Vĩnh Long',
            'districts' => array(
                486 => 'Bình Minh',
                487 => 'Bình Tân',
                488 => 'Long Hồ',
                489 => 'Mang Thít',
                490 => 'Tam Bình',
                491 => 'Trà Ôn',
                492 => 'Vũng Liêm',
                493 => 'Vĩnh Long',
            ),
        ),
        'NB' => array(
            'text' => 'Ninh Bình',
            'districts' => array(
                494 => 'Gia Viễn',
                495 => 'Hoa Lư',
                496 => 'Kim Sơn',
                497 => 'Nho Quan',
                498 => 'Yên Khánh',
                499 => 'Yên Mô',
                500 => 'Ninh Bình',
                501 => 'Tam Điệp',
            ),
        ),
        'PT' => array(
            'text' => 'Phú Thọ',
            'districts' => array(
                502 => 'Cẩm Khê',
                503 => 'Đoan Hùng',
                504 => 'Hạ Hòa',
                505 => 'Lâm Thao',
                506 => 'Phù Ninh',
                507 => 'Tam Nông',
                508 => 'Tân Sơn',
                509 => 'Thanh Ba',
                510 => 'Thanh Sơn',
                511 => 'Thanh Thủy',
                512 => 'Yên Lập',
                513 => 'Việt Trì',
                514 => 'Phú Thọ',
            ),
        ),
        'NT' => array(
            'text' => 'Ninh Thuận',
            'districts' => array(
                515 => 'Bác Ái',
                516 => 'Ninh Hải',
                517 => 'Ninh Phước',
                518 => 'Ninh Sơn',
                519 => 'Thuận Bắc',
                520 => 'Phan Rang - Tháp Chàm',
                521 => 'Thuận Nam',
            ),
        ),
        'PY' => array(
            'text' => 'Phú Yên',
            'districts' => array(
                522 => 'Đông Hòa',
                523 => 'Đồng Xuân',
                524 => 'Phú Hòa',
                525 => 'Sơn Hòa',
                526 => 'Sông Cầu',
                527 => 'Sông Hinh',
                528 => 'Tây Hòa',
                529 => 'Tuy An',
                530 => 'Tuy Hòa',
            ),
        ),
        'HNA' => array(
            'text' => 'Hà Nam',
            'districts' => array(
                531 => 'Bình Lục',
                532 => 'Duy Tiên',
                533 => 'Kim Bảng',
                534 => 'Lý Nhân',
                535 => 'Thanh Liêm',
                536 => 'Phủ Lý',
            ),
        ),
        'HT' => array(
            'text' => 'Hà Tĩnh',
            'districts' => array(
                537 => 'Cẩm Xuyên',
                538 => 'Can Lộc',
                539 => 'Đức Thọ',
                540 => 'Hương Khê',
                541 => 'Hương Sơn',
                542 => 'Kỳ Anh',
                543 => 'Lộc Hà',
                544 => 'Nghi Xuân',
                545 => 'Thạch Hà',
                546 => 'Vũ Quang',
                547 => 'Hà Tĩnh',
                548 => 'Hồng Lĩnh',
            ),
        ),
        'DDT' => array(
            'text' => 'Đồng Tháp',
            'districts' => array(
                549 => 'Huyện Cao Lãnh',
                550 => 'Châu Thành',
                551 => 'Hồng Ngự',
                552 => 'Lai Vung',
                553 => 'Lấp Vò',
                554 => 'Tam Nông',
                555 => 'Tân Hồng',
                556 => 'Thanh Bình',
                557 => 'Tháp Mười',
                558 => 'Sa Đéc',
                559 => 'Cao Lãnh',
                560 => 'Huyện Hồng Ngự',
            ),
        ),
        'ST' => array(
            'text' => 'Sóc Trăng',
            'districts' => array(
                561 => 'Cù Lao Dung',
                562 => 'Kế Sách',
                563 => 'Long Phú',
                564 => 'Mỹ Tú',
                565 => 'Mỹ Xuyên',
                566 => 'Ngã Năm',
                567 => 'Thạnh Trị',
                568 => 'Vĩnh Châu',
                569 => 'Sóc Trăng',
                570 => 'Châu Thành',
                571 => 'Trần Đề',
            ),
        ),
        'KT' => array(
            'text' => 'Kon Tum',
            'districts' => array(
                572 => 'Đăk Glei',
                573 => 'Đăk Hà',
                574 => 'Đăk Tô',
                575 => 'Kon Plông',
                576 => 'Kon Rẫy',
                577 => 'Ngọc Hồi',
                578 => 'Sa Thầy',
                579 => 'Tu Mơ Rông',
                580 => 'KonTum',
                581 => 'Ia H\'Drai',
            ),
        ),
        'QB' => array(
            'text' => 'Quảng Bình',
            'districts' => array(
                582 => 'Bố Trạch',
                583 => 'Lệ Thủy',
                584 => 'Minh Hóa',
                585 => 'Quảng Ninh',
                586 => 'Quảng Trạch',
                587 => 'Tuyên Hóa',
                588 => 'Đồng Hới',
                589 => 'Ba Đồn',
            ),
        ),
        'QT' => array(
            'text' => 'Quảng Trị',
            'districts' => array(
                590 => 'Cam Lộ',
                591 => 'Đa Krông',
                592 => 'Đảo Cồn cỏ',
                593 => 'Gio Linh',
                594 => 'Hải Lăng',
                595 => 'Hướng Hóa',
                596 => 'Triệu Phong',
                597 => 'Vĩnh Linh',
                598 => 'Đông Hà',
                599 => 'Quảng Trị',
            ),
        ),
        'TV' => array(
            'text' => 'Trà Vinh',
            'districts' => array(
                600 => 'Càng Long',
                601 => 'Cầu Kè',
                602 => 'Cầu Ngang',
                603 => 'Châu Thành',
                604 => 'Duyên Hải',
                605 => 'Tiểu Cần',
                606 => 'Trà Cú',
                607 => 'Trà Vinh',
            ),
        ),
        'HGI' => array(
            'text' => 'Hậu Giang',
            'districts' => array(
                608 => 'Châu Thành',
                609 => 'Châu Thành A',
                610 => 'Long Mỹ',
                611 => 'Phụng Hiệp',
                612 => 'Vị Thủy',
                613 => 'Ngã Bảy',
                614 => 'Vị Thanh',
            ),
        ),
        'SL' => array(
            'text' => 'Sơn La',
            'districts' => array(
                615 => 'Bắc Yên',
                616 => 'Mai Sơn',
                617 => 'Mộc Châu',
                618 => 'Mường La',
                619 => 'Phù Yên',
                620 => 'Quỳnh Nhai',
                621 => 'Sông Mã',
                622 => 'Sốp Cộp',
                623 => 'Thuận Châu',
                624 => 'Yên Châu',
                625 => 'Sơn La',
                626 => 'Vân Hồ',
            ),
        ),
        'BL' => array(
            'text' => 'Bạc Liêu',
            'districts' => array(
                627 => 'Đông Hải',
                628 => 'Giá Rai',
                629 => 'Hòa Bình',
                630 => 'Hồng Dân',
                631 => 'Phước Long',
                632 => 'Vĩnh Lợi',
                633 => 'Bạc Liêu',
            ),
        ),
        'YB' => array(
            'text' => 'Yên Bái',
            'districts' => array(
                634 => 'Lục Yên',
                635 => 'Mù Cang Chải',
                636 => 'Trạm Tấu',
                637 => 'Trấn Yên',
                638 => 'Văn Chấn',
                639 => 'Văn Yên',
                640 => 'Yên Bình',
                641 => 'Yên Bái',
                642 => 'Nghĩa Lộ',
            ),
        ),
        'TQ' => array(
            'text' => 'Tuyên Quang',
            'districts' => array(
                643 => 'Chiêm Hóa',
                644 => 'Hàm Yên',
                645 => 'Na Hang',
                646 => 'Sơn Dương',
                647 => 'Yên Sơn',
                648 => 'Tuyên Quang',
                649 => 'Lâm Bình',
            ),
        ),
        'DDB' => array(
            'text' => 'Điện Biên',
            'districts' => array(
                650 => 'Điện Biên',
                651 => 'Điện Biên Đông',
                652 => 'Mường Ảng',
                653 => 'Mường Chà',
                654 => 'Mường Nhé',
                655 => 'Tủa Chùa',
                656 => 'Tuần Giáo',
                657 => 'Điện Biên Phủ',
                658 => 'Mường Lay',
                659 => 'Nậm Pồ',
            ),
        ),
        'LCH' => array(
            'text' => 'Lai Châu',
            'districts' => array(
                660 => 'Mường Tè',
                661 => 'Phong Thổ',
                662 => 'Sìn Hồ',
                663 => 'Tam Đường',
                664 => 'Than Uyên',
                665 => 'Lai Châu',
                666 => 'Tân Uyên',
                667 => 'Nậm Nhùn',
            ),
        ),
        'LS' => array(
            'text' => 'Lạng Sơn',
            'districts' => array(
                668 => 'Bắc Sơn',
                669 => 'Bình Gia',
                670 => 'Cao Lộc',
                671 => 'Chi Lăng',
                672 => 'Đình Lập',
                673 => 'Hữu Lũng',
                674 => 'Lộc Bình',
                675 => 'Tràng Định',
                676 => 'Văn Lãng',
                677 => 'Văn Quan',
                678 => 'Lạng Sơn',
            ),
        ),
        'HG' => array(
            'text' => 'Hà Giang',
            'districts' => array(
                679 => 'Bắc Mê',
                680 => 'Bắc Quang',
                681 => 'Đồng Văn',
                682 => 'Hoàng Su Phì',
                683 => 'Mèo Vạc',
                684 => 'Quản Bạ',
                685 => 'Quang Bình',
                686 => 'Vị Xuyên',
                687 => 'Xín Mần',
                688 => 'Yên Minh',
                689 => 'Hà Giang',
            ),
        ),
        'BK' => array(
            'text' => 'Bắc Kạn',
            'districts' => array(
                690 => 'Ba Bể',
                691 => 'Bạch Thông',
                692 => 'Chợ Đồn',
                693 => 'Chợ Mới',
                694 => 'Na Rì',
                695 => 'Ngân Sơn',
                696 => 'Pác Nặm',
                697 => 'Bắc Kạn',
            ),
        ),
        'CB' => array(
            'text' => 'Cao Bằng',
            'districts' => array(
                698 => 'Bảo Lạc',
                699 => 'Bảo Lâm',
                700 => 'Hạ Lang',
                701 => 'Hà Quảng',
                702 => 'Hòa An',
                703 => 'Nguyên Bình',
                704 => 'Phục Hòa',
                705 => 'Quảng Uyên',
                706 => 'Thạch An',
                707 => 'Thông Nông',
                708 => 'Trà Lĩnh',
                709 => 'Trùng Khánh',
                710 => 'Cao Bằng',
            ),
        ),
    ]

];
